# Generated by Django 4.1.7 on 2023-03-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='locations_order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('initial_time', models.DateTimeField()),
                ('final_time', models.DateTimeField()),
                ('is_paid', models.BooleanField(default=False)),
                ('customer_id', models.IntegerField()),
                ('final_location_id', models.IntegerField()),
                ('initial_location_id', models.IntegerField()),
                ('vehicle_id', models.IntegerField()),
            ],
        ),
    ]
