# Generated by Django 4.1.2 on 2023-03-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="final_time",
            field=models.TimeField(null=True),
        ),
    ]
