# Generated by Django 4.1.2 on 2023-03-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_alter_order_final_time"),
    ]

    operations = [
        migrations.DeleteModel(
            name="locations_customuser_id",
        ),
        migrations.DeleteModel(
            name="locations_order",
        ),
        migrations.AlterField(
            model_name="order",
            name="final_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="initial_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
