# Generated by Django 4.1.7 on 2023-03-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_locations_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='locations_customuser_id',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
            ],
        ),
    ]
