# Generated by Django 4.1.7 on 2023-03-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_locations_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations_order',
            name='final_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='locations_order',
            name='initial_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
