# Generated by Django 4.1.2 on 2023-03-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0005_order_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="cost",
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=6, null=True
            ),
        ),
    ]
